analyzer:
  errors:
    invalid_use_of_protected_member: ignore
    missing_return: ignore
    dead_code: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: true
    prefer_single_quotes: true
