name: daily_dream
description: 每日梦境 - AI 梦境记录与分享

publish_to: 'none'

version: 1.0.6+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.0.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  speech_to_text: ^7.4.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
